
stages:
  - run_tests
  - image
  - script

run_tests:
  stage: test
  image: node:18-alpine
  script:
    - 
    - 

build_app:
  stage: ...
  script:
    - ...
  artifacts:
    paths:
      - ...
    expire_in: ...
  only:
    - ...
    - ...

deploy_staging:
  stage: ...
  script:
    - ...
  when: ...
  only:
    - ...
